import { packFromFiles } from "./packManifest";

// Trickcal-derived sounds and art, generated by `npm run assets` into a gitignored folder (plan §10).
// If the folder is empty the glob is empty and everything falls back to synth voices.
const files = import.meta.glob<string>("../assets/packs/trickcal/**/*.m4a", {
  eager: true,
  query: "?url",
  import: "default",
});

export default packFromFiles("trickcal", files);
