import { packFromFiles } from "./packManifest";

// Festa's frames and the VOICEVOX:No.7 sounds, generated by `npm run assets` and `npm run festa` and committed
// (published since 2026-09-27, owner's decision, plan §10). If the folder is empty, everything falls back to synth voices.
const files = import.meta.glob<string>("../assets/packs/trickcal/**/*.{m4a,webp,json}", {
  eager: true,
  query: "?url",
  import: "default",
});

export default { ...packFromFiles("trickcal", files), credits: ["VOICEVOX:No.7"] };
